name: 💡 Feature
description: Have a new idea/feature? Let us know...
title: "[FEATURE] <description>"
labels: ["enhancement", "feature", "hacktoberfest", "status: awaiting triage"]
body:
  - type: textarea
    attributes:
      label: What?
      description: Please describe your new feature or improvement clearly and concisely.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Why?
      description: Explain the problem or gap this feature aims to address (for example, "I'm always frustrated when [...]").
    validations:
      required: true
  - type: textarea
    attributes:
      label: How?
      description: Describe your proposed solution and include any relevant information or resources (like examples from other projects).
    validations:
      required: true

Before you get started, please take a moment to read the contributing guidelines: [Contributing Guide](https://github.com/manuelalferez/flowinance/blob/main/CONTRIBUTING.md).
